// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfV2BbleMOjIOfUrYbf8pg6xj4Bo5q7oA',
    appId: '1:172947325852:web:90e6d1a2fea51c51d4be59',
    messagingSenderId: '172947325852',
    projectId: 'saferapp-da89c',
    authDomain: 'saferapp-da89c.firebaseapp.com',
    storageBucket: 'saferapp-da89c.appspot.com',
    measurementId: 'G-4PC13Y2NK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmAeP-abVQE1dPa-iDdVTg0O-saxBN_qg',
    appId: '1:172947325852:android:a926a8012938d96ad4be59',
    messagingSenderId: '172947325852',
    projectId: 'saferapp-da89c',
    storageBucket: 'saferapp-da89c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi6c2nVhYzjoNtZY1nlvtntud-AdWPrag',
    appId: '1:172947325852:ios:06c7f4a4245c82ccd4be59',
    messagingSenderId: '172947325852',
    projectId: 'saferapp-da89c',
    storageBucket: 'saferapp-da89c.appspot.com',
    iosClientId: '172947325852-b04t7sblg6vhoctiqgm61g6loa6pa7fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.safer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi6c2nVhYzjoNtZY1nlvtntud-AdWPrag',
    appId: '1:172947325852:ios:06c7f4a4245c82ccd4be59',
    messagingSenderId: '172947325852',
    projectId: 'saferapp-da89c',
    storageBucket: 'saferapp-da89c.appspot.com',
    iosClientId: '172947325852-b04t7sblg6vhoctiqgm61g6loa6pa7fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.safer',
  );
}
